spring:
  jpa:
    database: postgresql
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
      properties:
        format_sql: true
    show-sql: true

  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://ec2-34-235-108-214.compute-1.amazonaws.com/d3sugaaegkp0hu
    username: ivuvwyezjfvphr
    password: 59e1f361b04ab0f0d136b97bf94724d439150748222f625140cf10c4fa1323f2
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres

jwt:
  secret-key: fast_campus.sns-application-2022.secret_key
  token:
    expired-time-ms: 2592000000 #(30days->ms)





